### ISSUE TITLE
Evaluation/Comparison screen: Need better handing of evaluation period (if one is set)

### ISSUE THREAD

**Issue by mwytang** [ubc/acj-versus#179]
Similar to Ticket #87. 

Questions to think about:
- What happens if the student have not finished the whole form?
- How much of a grace period should we allow?

Possible Solution:
- countdown timer as a warning
    - Where should we put the timer? - the evaluation form is longer than the answer form

**Comment by lenglund** [comment]
I think the evaluation is discarded if the student does not have something in all required fields. But perhaps instructors want to weigh in on this?

Can the timer follow the user as s/he scrolls down the page rather than having a static position?

**Comment by mwytang** [comment]
Refactor timer to get server time to adjust client's time

**Comment by lenglund** [comment]
Need to take a look at the wording for the timer tool tip.

**Comment by lenglund** [comment]
Server time is being used and wording has been adjusted for the timer currently in place for answering. However, the timer has not yet been implemented for comparing, so this issue remains open.

**Comment by andrew-gardener** [comment]
#307 adds a deadline timer for the comparison screen but it doesn't follow the screen as the user scrolls. 

The timer following the screen might not be as necessary once we implement #289 since the comparison screen won't be as long.

**Comment by lenglund** [comment]
Outstanding questions (applies to both answering and comparing):
What happens to my work when the deadline passes and I haven't saved or submitted but have filled in part or all of the form? Can I hit save or submit? It would be nice if we could give the user a "last change" to submit somehow (popup?), rather than the deadline passing and then they can't do anything.

What happens to my work when the deadline passes and I have saved but not submitted? Can I still submit what I saved? Maybe we could have this happen automatically (with communication to the user what will happen with their drafts)? I can see users remembering they had "done" an assignment, when in fact they had only saved the draft. Until we set up notifications (that would theoretically tell users a deadline is approaching and they have unfinished work), this seems like a sensible default behaviour...

Since we're caching the comparison dates, is there a way to force a refresh of the user's browser when the assignment has been updated, so if the instructor extends the deadline, this is reflected in what a student sees? Right now, I can only get updated dates (moved forward or backward in time) with a hard refresh. I can see a use case for an instructor giving extra time, but then not all users would see this without proper instruction/guidance.

**Comment by lenglund** [comment]
Timer placement does seem okay to me. The screen is shorter with the comparison workflow changes.

**Comment by andrew-gardener** [comment]
> What happens to my work when the deadline passes and I haven't saved or submitted but have filled in part or all of the form? Can I hit save or submit? It would be nice if we could give the user a "last change" to submit somehow (popup?), rather than the deadline passing and then they can't do anything.

There is currently a 1 minute grace period where they can still submit if they are already on the answer/comparison screens (applied to both answering and comparing). After the grade period, students cannot save drafts/submit anymore. We can extend the grace period/make it a assignment setting if it helps

> What happens to my work when the deadline passes and I have saved but not submitted? Can I still submit what I saved? Maybe we could have this happen automatically (with communication to the user what will happen with their drafts)? I can see users remembering they had "done" an assignment, when in fact they had only saved the draft. Until we set up notifications (that would theoretically tell users a deadline is approaching and they have unfinished work), this seems like a sensible default behaviour...

Maybe we could let instructors and teaching assistants see drafts and submit them for the student.

> Since we're caching the comparison dates, is there a way to force a refresh of the user's browser when the assignment has been updated, so if the instructor extends the deadline, this is reflected in what a student sees? Right now, I can only get updated dates (moved forward or backward in time) with a hard refresh (with the counter appearing and counting up in some cases). I can see a use case for an instructor giving extra time, but then not all users would see this without proper instruction/guidance.

I haven't gotten a chance to rework the front-end caching yet. Something we could add to a expiration time to cached data. Otherwise, cached information should be removed on end of session. I don't think there is a feasible way to directly expire the students cache when the teacher makes a change (it would be easier to just not cache assignments in this case)

**Comment by lenglund** [comment]
For now, we'll keep the 1-minute grace period and let drafts be simply drafts (not visible to instructors). We can ask for instructor input or see what feedback we get with this approach.

Should update:
- [ ] Text to students after countdown completes
- [ ] For now, disable caching on assignment (will revisit this later)

**Comment by lenglund** [comment]
Resolved for now. Related work to continue in #359.
